name: "Setup Genesys Cloud Tools"
description: "Installs Archy and the Genesys Cloud CLI"

runs:
  using: "composite"
  steps:
    - name: Install Archy
      run: |
        ARCHY_VERSION="v1.3.0"
        echo "Downloading Archy $ARCHY_VERSION..."
        wget -q https://github.com/GenesysCloudDevOps/archy/releases/download/$ARCHY_VERSION/archy-linux-glibc-amd64

        chmod +x archy-linux-glibc-amd64
        mv archy-linux-glibc-amd64 archy

        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

      shell: bash

    - name: Install Genesys Cloud CLI
      run: |
        echo "Installing Genesys CLI..."
        curl -L https://sdk-cdn.mypurecloud.com/cli/linux/amd64/latest/genesyscloud -o genesyscloud
        chmod +x genesyscloud
        mv genesyscloud gc

        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
      shell: bash
