name: "Setup Genesys Cloud Tools"
description: "Installs Archy and the Genesys Cloud CLI"
runs:
  using: "composite"
  steps:
    - name: Install Archy
      run: |
        ARCHY_VERSION="v2.0.1"
        wget -q https://github.com/GenesysCloudDevOps/archy/releases/download/$ARCHY_VERSION/archy-linux-x64
        chmod +x archy-linux-x64
        mv archy-linux-x64 archy
        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
      shell: bash

    - name: Install Genesys Cloud CLI
      run: |
        curl -L https://sdk-cdn.mypurecloud.com/cli/linux/amd64/latest/genesyscloud -o genesyscloud
        chmod +x genesyscloud
        mv genesyscloud gc
        echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
      shell: bash
