name: "Publish Archy Flow"
description: "Publishes an Architect flow using Archy"

inputs:
  architect-flow-path:
    description: "Path to the flow YAML"
    required: true
  architect-results-path:
    description: "Path to write results JSON"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login + Publish Flow
      env:
        ARCHY_CLIENT_ID: ${{ env.ARCHY_CLIENT_ID }}
        ARCHY_CLIENT_SECRET: ${{ env.ARCHY_CLIENT_SECRET }}
        ARCHY_ENVIRONMENT: ${{ env.ARCHY_ENVIRONMENT }}
      run: |
        echo "=== Archy Login ==="
        archy login \
          --client-id "$ARCHY_CLIENT_ID" \
          --client-secret "$ARCHY_CLIENT_SECRET" \
          --environment "$ARCHY_ENVIRONMENT" \
          --non-interactive

        echo "=== Archy Publish ==="
        archy publish-flow \
          --file "${{ inputs.architect-flow-path }}" \
          --overwrite \
          --results-file "${{ inputs.architect-results-path }}" \
          --overwriteResultsFile \
          --non-interactive

        echo "=== Results ==="
        cat "${{ inputs.architect-results-path }}"
      shell: bash
